version: '3.9'
services:
    mongodb:
        image: mongo:5.0.8
        ports:
         - 27017:27017
        volumes:
 #           - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
  #          - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
             - ./database/db:/data/db
             - ./database/dev.archive:/Databases/dev.archive
             - ./database/production:/Databases/production
 #       environment:
 #        - MONGO_INITDB_ROOT_USERNAME=admin
 #        - MONGO_INITDB_ROOT_PASSWORD=password
    mongo-express:
        image: mongo-express:0.54.0
        ports:
         - 8181:8081
        environment:
 #        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
 #        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
         - ME_CONFIG_MONGODB_SERVER=mongodb
                