server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  ssl:
    enabled: true
    keyStoreType: jks
    key-store: keystore.jks
    key-store-password: changeit
#logging:
  ## pattern:
  ## console: %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n
  #level:
    #root: DEBUG
   # com.houselogiq: DEBUG
   # org.springframework.data: INFO
    #org.mongodb:
    #  core:
      #  MongoTemplate: DEBUG
#mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: RealEstate
      auto-index-creation: true
      #username: 465   587
      #password: nhicugdncaivfcny
  mail:
    host: smtp.mail.yahoo.com
    port: 465
    username: mbm_449@yahoo.com
    password: ehacsvdqhuowiqol
    transport:
      protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
    smtp:
      debug: true
logiq:
  verify:
    message:
      subject: Representation Invitation
  otp:
    message:
      #from: mbehdadm@yahoo.com
      subject: Sign in One Time Password
      body: "
            Welcome to HouseLogiQ by RE/MAX Hallmark! \n
            Your unique password is: {} \n
            Enter your password on the login page to get started '\n'
        "

repliers:
  accessToken: WFNUnFKbh3SVkXrXUbx65WwWH47X2S
  baseUrl: https://sandbox.repliers.io
  listings: /listings
  defaultResultsPerPage: 1000
  defaultPageNum: 1
  updatedOn:
  status:

